web:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_DATABASE: minhaConta
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DB_CONNECTION: pgsql
db:
    image: postgres
    environment:
        # with mysql
        #MYSQL_DATABASE: dbname
        #MYSQL_USER: username
        #MYSQL_PASSWORD: p455w0rd

        # with postgres
        POSTGRES_DB: minhaConta
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
